FROM node:16
WORKDIR /backend
RUN npm install -g firebase-tools

ADD functions/package*.json functions/
RUN npm --prefix ./functions install ./functions --force

COPY . ./
CMD ["npm", "run", "serve", "--prefix", "./functions"]